version: "3.0"

services:
  server:
    container_name: main_bot
    build:
      context: .
    command: tail -F anything
  server-2:
    container_name: other_bot
    build:
      context: .
    command: tail -F anything
